# Generated by Django 3.2.7 on 2021-09-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='date',
            new_name='day',
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='trainer',
            field=models.ManyToManyField(blank=True, to='classes.Trainer'),
        ),
    ]
