# Generated by Django 3.2.7 on 2021-10-03 00:08

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20210930_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
