# Generated by Django 3.2.7 on 2021-10-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20211003_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
