# Generated by Django 3.2.7 on 2021-10-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20211012_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='short',
            field=models.TextField(blank=True),
        ),
    ]
