# Generated by Django 3.2.7 on 2021-10-15 23:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_gymclass_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='bio',
            field=tinymce.models.HTMLField(),
        ),
    ]
